<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */
// @codingStandardsIgnoreFile
//"swatchRenderer": {
?>
<?php
/** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */
?>
<div class="swatch-opt" data-role="swatch-options-qv"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options-qv]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct')) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= $block->getJsonSwatchSizeConfig() ?: 0 ?>,
                "showTooltip": 1,
                "mediaGallerySelector": "#quickview-gallery"
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>
